Switch Vagrant from `rvm` to `rbenv`
MushroomObserver/developer-startup pull request #43
Opened 2022-12-22 05:03 UTC by nimmolo

Wow. So easy.

2022-12-22 05:09 UTC, nimmolo commented
@JoeCohen - I'm not able to upload the box I built with this Vagrantfile at the moment, because i'm at a different location, but I believe if you use it to build yourself a new box locally, it'll be smooth sailing. 

Be sure to first `vagrant halt; vagrant destroy`. Also, I recommend to delete all machines manually from the directory `developer-startup/.vagrant/machines`, as well as `remove` any machines you may find in the Virtual Box GUI. Then run

`vagrant global-status --prune` 

to be sure everything's gone.

Then , with this Vagrantfile in `/developer-startup`, you can run `vagrant up clean-focal`.

2022-12-24 21:38 UTC, nimmolo commented
@raysuelzer Noticed your PR. 
Maybe I should merge this Vagrantfile update first to avoid conflicts, or please let me know if anything here could be improved for what you're doing. Basically `rvm` has given us a lot of trouble, and `rbenv` seems to be much better maintained and designed.

As far as I know, though, nobody has tested it — if you get a chance please do build and test a box built with this Vagrantfile. I may be able to upload a box to the images server, if that's easier.

2022-12-25 00:10 UTC, pellaea commented
One note: If you are starting fresh it can't find ./mushroomobserver/.ruby-version.  Maybe put that in . so that it doesn't have to already have the mo codebase installed?

2022-12-25 00:52 UTC, pellaea commented
It also fails later on if you do not have the codebase already cloned.  I'm getting the impression that you expect this to be the case?  Maybe add a check for it early on, and tell the user how to install the codebase (and where!) if they have not already done so.

2022-12-25 01:00 UTC, pellaea commented
Hmmm, looks like it works for me otherwise!

I had an outstanding db migration that I needed to do after running mo-dev.  Would it be worth adding a "rake db:migrate" on general principle to mo-dev?   I guess they will learn soon enough anyway, first time they run any rails command.  Yeah, I'd probably leave it the way it is

2022-12-25 01:05 UTC, pellaea requested changes
Do something about the case of the user not having the codebase installed yet, but otherwise this looks great to me.

2022-12-25 01:09 UTC, pellaea commented
Hold on.  I see virtualbox running on my system.  It shouldn't be, right???  What did I do wrong?

I attempted to check out this PR, that failed, so I just downloaded the new version of Vagrantfile, the only file that changed, then followed the instructions in the readme.  vagrant up, vagrant ssh, mo-dev /vagrant  Did this just provision a new virtualbox machine??  Yes, that's exactly what this did.  I thought this PR was supposed to use something else, not virtualbox.

2022-12-25 01:45 UTC, JoeCohen commented
That wasn't my impression (though I haven't looked at the PR).
I thought it was changing only the ruby version manager (from rvm to rbenv).

On Sat, Dec 24, 2022 at 8:09 PM Jason Hollinger ***@***.***>
wrote:

> Hold on. I see virtualbox running on my system. It shouldn't be, right???
> What did I do wrong?
>
> I attempted to check out this PR, that failed, so I just downloaded the
> new version of Vagrantfile, the only file that changed, then followed the
> instructions in the readme. vagrant up, vagrant ssh, mo-dev /vagrant Did
> this just provision a new virtualbox machine?? Yes, that's exactly what
> this did. I thought this PR was supposed to use something else, not
> virtualbox.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MushroomObserver/developer-startup/pull/43#issuecomment-1364604809>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAALDFDEHUU5COM3NZCJYNDWO6NGDANCNFSM6AAAAAATGKG5VQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-25 01:59 UTC, pellaea commented
Okay, I misread an earlier email, I guess.  Sorry!

On Sat, Dec 24, 2022 at 8:46 PM Joseph D. Cohen ***@***.***>
wrote:

> That wasn't my impression (though I haven't looked at the PR).
> I thought it was changing only the ruby version manager (from rvm to
> rbenv).
>
> On Sat, Dec 24, 2022 at 8:09 PM Jason Hollinger ***@***.***>
> wrote:
>
> > Hold on. I see virtualbox running on my system. It shouldn't be, right???
> > What did I do wrong?
> >
> > I attempted to check out this PR, that failed, so I just downloaded the
> > new version of Vagrantfile, the only file that changed, then followed the
> > instructions in the readme. vagrant up, vagrant ssh, mo-dev /vagrant Did
> > this just provision a new virtualbox machine?? Yes, that's exactly what
> > this did. I thought this PR was supposed to use something else, not
> > virtualbox.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/MushroomObserver/developer-startup/pull/43#issuecomment-1364604809
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AAALDFDEHUU5COM3NZCJYNDWO6NGDANCNFSM6AAAAAATGKG5VQ
> >
> > .
> > You are receiving this because you were mentioned.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MushroomObserver/developer-startup/pull/43#issuecomment-1364609871>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAYTNNPOCEFROZUVQOUZ3B3WO6RN5ANCNFSM6AAAAAATGKG5VQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-12-25 02:25 UTC, pellaea commented
One more thing, sorry.  I just noticed that you tack on "test_secret: magic" to the credentials file, which causes it to change, so that the user needs to revert it by hand before checking in their next commit.  Would you mind having it automatically reverting it so that's unnecessary?  (It might not be a bad idea to insert a blank line between that and "rails lang:update" so that it's clear that the credentials test has nothing to do with the language update.

2022-12-25 03:17 UTC, nimmolo commented
Thanks for checking it out. I will add a backup file for `mushroom-observer/.ruby-version`
I think that `test_secret: magic` is something Nathan added. I don't know what it does!

Joe's right, it's just changing from rvm to rbenv. It's still a VirtualBox/Vagrant box, not Docker. I would recommend updating VirtualBox to 7.0.4 or whatever's current.

2022-12-25 03:29 UTC, pellaea commented
Yeah, I misread an old email saying (I thought) that you were switching
from "virtualbox" to "rbenv".  I didn't know what that meant, but I went
with it!  Obviously, either it was a typo, or I misread the email.  Doesn't
matter now!

On Sat, Dec 24, 2022 at 10:18 PM andrew nimmo ***@***.***>
wrote:

> Thanks for checking it out. I will add a backup file for
> mushroom-observer/.ruby-version
> I think that test_secret: magic is something Nathan added. I don't know
> what it does!
>
> Joe's right, it's just changing from rvm to rbenv. It's still a
> VirtualBox/Vagrant box, not Docker. I would recommend updating VirtualBox
> to 7.0.4 or whatever's current.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MushroomObserver/developer-startup/pull/43#issuecomment-1364619848>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAYTNNPTIQQEOGUSUXEQUY3WO64G3ANCNFSM6AAAAAATGKG5VQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-12-28 20:03 UTC, raysuelzer commented
@nimmolo I didn't make changed to the vagrant file. One thing to note is that I had to disable the serial port in the Virtual Box GUI for the machine to work. It was trying to write log files to a non-existent location. Disabling it didn't seem to impact anything other than allowing the machine to boot. If there is a way to do this in the config file that would be cool.

2022-12-28 23:08 UTC, nimmolo commented
@raysuelzer Thanks for tracking that down. I wonder if that was happening to me too. I didnt have any trouble getting the machine to boot, but when first building the vagrant box, i remember VB had several machines running by the end, and that didnt seem right. 

Would you be willing to make a commit to this PR, adding the config to disable the serial port?

2023-01-07 23:07 UTC, nimmolo commented
@pellaea re: `test_secret: magic` I'll be happy to put that revert in, or delete the line, but i don't understand how to make it revert. I honestly have no idea what that line is doing!

2023-01-07 23:21 UTC, nimmolo commented
@raysuelzer re: "It was trying to write log files to a non-existent location" - maybe, should the script create the log file so it has somewhere to write? if you know where to fix this please do commit to this PR. 

If not I can just merge and we can fix when we figure out.

@pellaea  - This should be fixed, but please review. I'm both checking for the file's existence in the Vagrantfile, and adding `mushroom-observer/.ruby-version` to the repo (and telling gitignore not to ignore it, but ignore everything else in /mo).

> Do something about the case of the user not having the codebase installed yet, but otherwise this looks great to me.

2023-01-30 23:37 UTC, nimmolo commented on mo-dev
>  EDITOR='echo "test_secret: magic" >> ' rails credentials:edit
@pellaea - I think this is what you're talking about in the comments...

@mo-nathan - I believe you added this line, but I don't believe I understand what it's doing. 
Is this just providing a backup value for the credentials in case someone doesn't have them installed?

2023-01-31 01:24 UTC, merged